### ISSUE TITLE
My Rpi does not set the argon fan in i2cset -y 1 0x01a but in i2cset -y 3 0x01a

### ISSUE THREAD

**Issue by juancameijeiras** [adamoutler/HassOSArgonOneAddon#18]
I have been going a little crazy because of this and figured out that my Debian 10 buster installation on the Pi does not detect the argon case in the i2c where all the code has been written, it normally defaults to 0, 1 or 2 but mine is in 3! I can successfully control the fan by running i2cset -y 3 0x01a 0x64 (100%) or i2cset -y 3 0x01a 0x00 (0%). Is there a way to modify the code so that in the configuration in Home Assistant add-on one can change the i2c address? Cheers and great work!

**Comment by adamoutler** [comment]
You'll need to look at how to remap the i2c device. You may be able to do it with udev rules or a script to delete the i2c and mknod the right one in the other /dev name.  This uses /dev/i2c-2 I believe.  You'll need to remap it there to use this tool.  Otherwise you can fork the project and make your own.

**Comment by juancameijeiras** [comment]
Thanks but could not solve it using debian so I just installed rpios for the time being as it maps correctly the i2c board and devices from the argon daughter board.
