### ISSUE TITLE
24.2 Update Not Working

### ISSUE THREAD

**Issue by robertoleonardo** [adamoutler/HassOSArgonOneAddon#31]
When i try to install teh brand new update, i get the following error: 

Can't install 7d06b5a0/aarch64-addon-argon_one_temp:24.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=24.2&fromImage=7d06b5a0%2Faarch64-addon-argon_one_temp&platform=linux%2Farm64: Not Found ("pull access denied for 7d06b5a0/aarch64-addon-argon_one_temp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")

**Comment by Daali** [comment]
I get the same error on attempting to update.  denied: requested access to the resource is denied

**Comment by andreasc1** [comment]
same with me:

`homeassistant.exceptions.HomeAssistantError: Error updating ArgonOne Active Cooling: Can't install 7d06b5a0/aarch64-addon-argon_one_temp:24.2: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=24.2&fromImage=7d06b5a0%2Faarch64-addon-argon_one_temp&platform=linux%2Farm64: Not Found ("pull access denied for 7d06b5a0/aarch64-addon-argon_one_temp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied")`

**Comment by riedlem** [comment]
same here as well

**Comment by adamoutler** [comment]
Sorry.  I was doing work with a new Linear mode addon.  Give me a bit to get things corrected.

**Comment by adamoutler** [comment]
So, I just checked on my instance and it does work, but it has to generate the dockerfile instead of download from dockerhub.  I recommend uninstalling and reinstalling until the problem is corrected.  I believe it should be fairly quickly.  There's either some permission changes or some adaptation that needs to happen to specify paths when two addons exist in the same directory.

**Comment by adamoutler** [comment]
The addon is back and operational with images on V25.  If you uninstalled and reinstalled during the issue, I recommend you uninstall and reinstall to update to v25.   The v24.2, and v24.3 were using raw-docker builds on your machine.  The V25 is back to using images.  

The difference is an image takes less than 1 second to download and upgrade.  the raw docker build takes about 10 seconds to download, build, and upgrade.   Either way you'll get the same software, but uninstall and reinstall to activate the docker images. 

Also, I'd like to draw attention to this new addon in the same repo, since the changes from it caused this problem.  
![image](https://user-images.githubusercontent.com/527919/174501419-410c8d90-0fda-4a9b-ad4e-5c53de81cc80.png)

It's basically the same as the standard Active Cooling addon, but it uses a linear algorithm which steps the fan up in increments of 1 from 0-254 based on minimum and maximum temperature.  This may be a good option.  However, it does not currently have an image so updates are slower to install. I'll work on that soon. 
![image](https://user-images.githubusercontent.com/527919/174501499-ce3f6671-2fc8-451d-b875-2c08ee934b86.png)
