### ISSUE TITLE
Entity not available

### ISSUE THREAD

**Issue by haforme** [adamoutler/HassOSArgonOneAddon#4]
Sometimes when I Restart Hass I receive a "Entity not available: sensor.argon_one_addon_fan_speed" message that occurs and will occasional clear by itself.  Today its been 30 minutes and it is still persist.  If I restart the addon it clears.
I an running:
HASSOS version 2021.3.3
ArgonOne Active Cooling version 0.19
Thank-you

**Comment by adamoutler** [comment]
It should recreate the entity at reboot. As soon as the fan addon comes up it requests HA to create the entity.  The same process is used every time fan speed changes. However, the fan will never exist at the time HA comes up because it is not a real entity.  It is just an API entry.   I can't fix this error message without an integration and I'm not planning to make an integration.  Can't/won't fix.
